import * as config from "../config.json";

export const FILE_VISIBILITY = config.VIEW_ID;

export const FileVisibilityActions = {
  // Context Options
  HIDE: `${FILE_VISIBILITY}.${config.HIDE}`,
  HIDE_FILE_EXTENSION: `${FILE_VISIBILITY}.${config.HIDE_FILE_EXTENSION}`,
  HIDE_FILE_NAME: `${FILE_VISIBILITY}.${config.HIDE_FILE_NAME}`,

  // TreeView Actions
  HIDE_ALL: `${FILE_VISIBILITY}.${config.HIDE_ALL}`,
  SHOW_ALL: `${FILE_VISIBILITY}.${config.SHOW_ALL}`,
  TOGGLE_SELECTED: `${FILE_VISIBILITY}.${config.TOGGLE_SELECTED}`,
  REFRESH: `${FILE_VISIBILITY}.${config.REFRESH}`,

  // TreeItem Actions
  TOGGLE_ROW_VISIBILITY: `${FILE_VISIBILITY}.${config.TOGGLE_ROW_VISIBILITY}`,
  REMOVE: `${FILE_VISIBILITY}.${config.REMOVE}`,
  TOGGLE_FAVORITE_ON: `${FILE_VISIBILITY}.${config.TOGGLE_FAVORITE_ON}`,
  TOGGLE_FAVORITE_OFF: `${FILE_VISIBILITY}.${config.TOGGLE_FAVORITE_OFF}`,
  TOGGLE_SEARCH_ON: `${FILE_VISIBILITY}.${config.TOGGLE_SEARCH_ON}`,
  TOGGLE_SEARCH_OFF: `${FILE_VISIBILITY}.${config.TOGGLE_SEARCH_OFF}`,
  TOGGLE_LOCK_ON: `${FILE_VISIBILITY}.${config.TOGGLE_LOCK_ON}`,
  TOGGLE_LOCK_OFF: `${FILE_VISIBILITY}.${config.TOGGLE_LOCK_OFF}`,

  // TreeFolder Actions
  TOGGLE_FOLDER_LOCK: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_LOCK}`,
  TOGGLE_FOLDER_UNLOCK: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_UNLOCK}`,
  TOGGLE_FOLDER_HIDE: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_HIDE}`,
  TOGGLE_FOLDER_SHOW: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_SHOW}`,
  TOGGLE_FOLDER_SEARCH_ON: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_SEARCH_ON}`,
  TOGGLE_FOLDER_SEARCH_OFF: `${FILE_VISIBILITY}.${config.TOGGLE_FOLDER_SEARCH_OFF}`,
} as const;

export type FileVisibilityActions =
  (typeof FileVisibilityActions)[keyof typeof FileVisibilityActions];
